apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: isdckft-com-tls
spec:
  secretName: isdckft-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: isdckft.com
  dnsNames:
    - isdckft.com
    - www.isdckft.com
